### PR TITLE
Add hero flagging hotkey

### PR DESCRIPTION
**Pull request by PostCrafter**
Adds functionality to flag heroes around the player, which makes it possible to hotkey hero formations.
Orientation is based on currently selected target or player rotation if no target is selected.
Flagging an already flagged hero instead unflags that hero.

There's plenty room for improvement (like an actual Formation Manager), but this is a decent first step.

### CODE REVIEW

**Comment by HiImFlo** [comment]
This has been wished for for a couple of years and can be a feature with a lot of impact on casual PvE. Any implementation of this is great, thanks a lot! I am sure many people will really like this if it is added, since it removes one of the really tedious parts of playing with heroes.

There have been at least 2 issues regarding this, idk if you have read those but good ideas are in there: #61 and #239 

Imo the dream would be that people could use both minimap as well as a flag in 3D (with changed mouse cursor), flag the hero formation to any point they like and have the heros be oriented towards the current target like you said.

**Comment by PostCrafter** [comment]
I have looked at those issues and took some inspiration (like flagging towards current target) already.

I'm currently not sure how to properly interact between mulitple modules such as pressing a hotkey/UI button to trigger a minimap formation flag on next click. Any pointers to that would be appreciated. Once that issue is out of the way I could look into adding a separate module for formation flagging.

**Comment by 3vcloud** [comment]
Take a look at the `/flag` chat command

**Comment by 3vcloud** [comment]
Sorry that was a stupid reply. You could make the var that the minimap uses a public variable and go from there, but tbh I think that you should try and find the actual in-game hook for flagging heros and use that, then we could have the minimap use it aswell instead of its own internal variable to see if the user is currently flagging. You'd be able to flag both in-game and on the minimap that way.

**Comment by reduf** [comment]
It's great that you do PR, I respect that a lot, but I would recommend to do it on @3vcloud repo. I'm merely maintaining the project and maybe planning to merge @3vcloud in our repo, so a single branch exist.

**Comment by 3vcloud** [comment]
Added from your repo via https://github.com/HasKha/GWToolboxpp/commits/7af99d65374c8aaffd46750914b5d4abf7dedccb

**Pull request closed without merging**
