### PR TITLE
Added /pings chat command

### PR DESCRIPTION
**Pull request by tjubutsi**
I'm not too sure about some stuff but at least it's a few things already done.

### CODE REVIEW

**Comment by tjubutsi** [comment]
So toggle between normal and 10% visible pings? Something like that?

**Comment by HasKha** [comment]
yea, that could be done as well

**Comment by tjubutsi** [comment]
Is it useful to keep this? I don't think I know enough to create the whole settings thing myself.

**Comment by HasKha** [comment]
yes, I'll merge and work on it when I have time. I prioritized the other PR despite being later as we've been actually thinking on that for a while longer.

**Comment by HasKha** [comment]
Ended up implementing it with a different solution, check the above commit for details. Closing.

**Pull request closed without merging**
