### PR TITLE
feat: hide equipped and customized items

### PR DESCRIPTION
**Pull request by ChandlerFerry**
- Hides set equipped items from merchant
- Hides customized items from merchant

### CODE REVIEW

**Comment by 3vcloud** [comment]
Isn’t there a tab in the merchant window to hide your equipped items?

**Comment by ChandlerFerry** [comment]
This functions as directly "equipped":
image

`item->equipped` is specifically meant to remove items that are equipped in a set that is not currently in use:
image

_Note the Zealous Gazing Scythe of Enchanting/Fiery Grim Scythe/Barbed Flatbow with icons identifying that they are equipped in a set._

**Comment by DubbleClick** [comment]
Don't have time to check if this works without side effects, but assuming it does, it's a good addition.

**Comment by 3vcloud** [comment]
image

**Pull request merged**
