### PR TITLE
Write Party Damage by Clicking

### PR DESCRIPTION
**Pull request by franneck94**
By clicking on the party damage window the damage is written to the party chat.
This would be an alternative to the chat command.

Note: I am not sure if i should add an option for this to enable/disable.

### CODE REVIEW

**Comment by HiImFlo** [comment]
Of course this should disabled by default. What you probably would want to do is only ping on Ctrl+Click, like the health monitor does.

**Comment by 3vcloud** [comment]
1. Should be ctrl + click as @HiImFlo mentioned
2. Should only write the current row to chat instead of triggering a mess of messages that you can't stop if you've accidentally ctrl + clicked in that area

3. Also please keep functional commits separate from coding style commits so I can more easily see whats what :)

**Comment by franneck94** [comment]
1.) Of course, I will implement this today.
2.) So you mean writing only the damage of a single player?

**Comment by 3vcloud** [comment]
Yep, the player can ctrl click each row themselves if they really want to

**Comment by franneck94** [comment]
1.) and 2.) are now implemented

**Pull request merged**
