### PR TITLE
remove intance_start from objectiveset

### PR DESCRIPTION
**Pull request by DubbleClick**
I don't know why this was even ever used

### CODE REVIEW

**Comment by 3vcloud** [comment]
A run is started when you've loaded in; you might load in slower than other people so objective 1 could start late. I think this would throw the whole run time off a bit if you loaded in late.

**Comment by 3vcloud** [comment]
Yeh looks like this now calculates everything from run start i.e. when the map loaded for your player - this is wrong and it needs to be against the instance time, hence the calculation for `done`

**Comment by DubbleClick** [comment]
yeah that's why I came to it in the first place, we shouldn't be using 3 different timers but only one that is actually relevant

**Comment by DubbleClick** [comment]
(run_time_point_started already uses the TimerWidgets time now btw)

**Comment by 3vcloud** [comment]
There will almost never be a situation when the run start time point is equal to the instance start time point unless you're plugged into the datacenter. The objective timer has been combed over on this one and I think the timestamps will be messed up if you use this logic now.

**Comment by DubbleClick** [comment]
wouldn't that mean that the instancetimer/timerwidget is wrong?

**Comment by 3vcloud** [comment]
The timer widget should start its instance timer from the moment the map starts loading, which is a deliberate change made around a year ago because the GW server's instance time is not always as accurate (there is a feature in the timer widget to show both of these timestamps on screen to show the difference). This timestamp should be treated as the instance time, and any other timestamps recorded within the instance based off of it.

**Comment by DubbleClick** [comment]
I'm happy to switch back to instance time for everything by the way. I just don't want 3 different timers ticking when only one is useful for the end completion time and another is factually "correct"

**Comment by DubbleClick** [comment]
> This timestamp should be treated as the instance time, and any other timestamps recorded within the instance based off of it.

In that case this should just be fine now, no?

**Comment by 3vcloud** [comment]
No, times are now going to be relative to when the ObjectiveSet was created rather then when the map was created, which in effect depends more on individual player load times than the team's achievement in the map

**Comment by DubbleClick** [comment]
So what's the solution where we use *one* time instead of three

**Comment by DubbleClick** [comment]
> The timer widget should start its instance timer from the moment the map starts loading

To make it clear again, this is also the time that the run_start_time_point from the ObjectiveSet uses

**Comment by 3vcloud** [comment]
No, it uses `TimerWidget::Instance().GetRunTimeStart()` which is different to `TimerWidget::Instance().GetTimeElapsedMs()`

**Comment by DubbleClick** [comment]
`TimerWidget::Instance().GetTimeElapsedMs()` uses that very time point for its calculation

**Comment by 3vcloud** [comment]
```cpp
std::chrono::milliseconds TimerWidget::GetMapTimeElapsed() {
    if (!is_valid(instance_started)) {
        // Can happen if toolbox was started after map load
        instance_started = now() - milliseconds(GW::Map::GetInstanceTime());
    }
    return duration_cast<milliseconds>(now() - instance_started);
}
...
unsigned long TimerWidget::GetRunTimeStart() const
{
    if (!is_valid(run_started)) {
        return static_cast<unsigned long>(-1);
    } 
    return static_cast<unsigned long>(duration_cast<milliseconds>(run_started.time_since_epoch()).count());
}
...
unsigned long TimerWidget::GetMapTimeElapsedMs() { return static_cast<unsigned long>(GetMapTimeElapsed().count()); }
```
`GetRunTimeStart()` is not the same as `GetMapTimeElapsedMs()`

**Comment by DubbleClick** [comment]
```cpp
std::chrono::milliseconds TimerWidget::GetTimer() {
    if (use_instance_timer) {
        return milliseconds(instance_timer_valid ? GW::Map::GetInstanceTime() : 0);
    }
    return GetRunTimeElapsed();
}
```

I've updated the code to check use_instance_timer

**Comment by 3vcloud** [comment]
1. The timer widget is supposed to show you on-screen how long the instance has been up.
2. All objectives are relative to when the instance was started, not the run. This is because players load in at different times and their client would start the objective sets later if they loaded in later.
3. Some runs span 1 or more maps, and so the run time could be greater than the instance time.

Is there something not working right with the objective timer that needs all of these changes?

**Comment by DubbleClick** [comment]
> Is there something not working right with the objective timer that needs all of these changes?

As things were, the ObjectiveSet uses a different time than the TimerWidget and the Objective completions use yet another time. That's three different times when only one is actually relevant to us (either the instance time or the run time used for gwscr).

**Comment by DubbleClick** [comment]
> `GetRunTimeStart()` is not the same as `GetMapTimeElapsedMs()`

TimerWidget::GetMapTimeElapsed() has zero references throughout the project, by the way. It's unused

**Comment by 3vcloud** [comment]
I'm just going to merge this in, we can test and fix later if needed

**Comment by DubbleClick** [comment]
I've already been testing it for what it's worth and it's now working as expected  - ObjectiveSet, Objective and TimerWidget use the same time points.

**Pull request merged**
