### PR TITLE
Additional Range Indicators

### PR DESCRIPTION
**Pull request by PostCrafter**
This adds a few additional range indicators:
- Shadowstep aggro range: 1010 (aggro range) around your shadow step marker, to help with not breaking the stance into aggro
- Rezz aggro range: 1010 (aggro range) around your targeted dead ally, to help with rezzing them outside aggro
- Chain aggro range: 700 range around targeted foes, to help seeing when it is safe to be attacked

### CODE REVIEW

**Comment by PostCrafter** [comment]
I'm sure there's improvements to be made regarding the rendering, so please leave some feedback, as this is my first time doing anything like this.

**Comment by HasKha** [comment]
I like shadowstep and res aggro ranges, but having a constant range indicator around your target could add visual noise while not being particularly useful to a lot of players. Maybe we can default it to disabled (transparent). 

I can look over the rendering but it looks okay at a first glance (and it's been a while since I touched that code :p )

**Comment by PostCrafter** [comment]
Sure, I'll split up the ranges, so I can actually assign different colors and default it to transparent for chain aggro.

**Comment by PostCrafter** [comment]
I've been using this feature for almost 2 weeks now and like it quite a bit.
Before actually merging this we might want to have a look at the default values, as most people are probably not interested in chain aggro range.

**Comment by Hour-of-the-Owl** [comment]
I'm mildly triggered by the colours going ARGB instead of RGBA... but more concerned that my HoS line is replaced by a weird cross that always points east. Apart from this I've encountered no problems.

**Comment by 3vcloud** [comment]
Would've merged this in yesterday but theres still a lot of conflicts and I didn't have the time

**Comment by BearsMan** [comment]
@PostCrafter u may wanna update these :)

**Comment by 3vcloud** [comment]
@PostCrafter I've implemented these with a few modifications in https://github.com/HasKha/GWToolboxpp/commits/737907aa53d54305617b5ba4100a539c8b1c7d47 
 - chain aggro range is disabled by defualt, the other 2 are enabled by default

**Pull request closed without merging**
