### PR TITLE
feat: add duping window

### PR DESCRIPTION
**Pull request by MikeJerred**
Added a window to help with DoA duping

### CODE REVIEW

**Comment by BearsMan** [comment]
Nice job Mike! This should be in Dev branch not Master, but I am sure it will be worked out soon.

**Comment by MikeJerred** [comment]
@BearsMan thanks, I switched base and there are no conflicts so should be fine

**Comment by BearsMan** [comment]
> @BearsMan thanks, I switched base and there are no conflicts so should be fine

Yea, as long as you see the words no conflicts with your code. Then that means it will most likely be put into the master branch after it has been tested in dev branch

**Comment by BearsMan** [comment]
Yea, as long as you see the words no conflicts with your code. Then that means it will most likely be put into the master branch after it has been tested in dev branch

**Comment by 3vcloud** [comment]
See https://github.com/HasKha/GWToolboxpp/commit/56b647b986f0a936f37bfab8a3dc63ef4cc43c9c for post merge changes

**Comment by 3vcloud** [comment]
Its worth also noting that this will only work properly when GW is the focussed window; the Draw() and Update() calls don't run every frame if the game isn't being played, so need to think about hooking StoC packets to maintain the vectors outside of the draw loop

**Pull request closed without merging**
